spec_name: Raft
constants:
- name: Server
  value: '{"n1", "n2", "n3"}'
- name: Value
  value: '{"v1", "v2", "v3"}'
- name: Nil
  value: '"Nil"'
- name: NoLimit
  value: '3'
variables:
- name: currentTerm
  default_value: '[s \\in Server |-> 0]'
- name: votedFor
  default_value: '[s \\in Server |-> Nil]'
- name: log
  default_value: '[s \\in Server |-> <<>>]'
- name: commitIndex
  default_value: '[s \\in Server |-> 0]'
- name: state
  default_value: '[s \\in Server |-> "Follower"]'
- name: leaderId
  default_value: '[s \\in Server |-> Nil]'
- name: nextIndex
  default_value: '[s \\in Server |-> [t \\in Server |-> 1]]'
- name: matchIndex
  default_value: '[s \\in Server |-> [t \\in Server |-> 0]]'
- name: votesGranted
  default_value: '[s \\in Server |-> {}]'
- name: votesRejected
  default_value: '[s \\in Server |-> {}]'
- name: electionElapsed
  default_value: '[s \\in Server |-> 0]'
- name: heartbeatElapsed
  default_value: '[s \\in Server |-> 0]'
- name: randomizedElectionTimeout
  default_value: '[s \\in Server |-> 3]'
- name: messages
  default_value: '{}'
- name: readStates
  default_value: '[s \\in Server |-> <<>>]'
- name: pendingReadIndexMessages
  default_value: '[s \\in Server |-> <<>>]'
- name: leadTransferee
  default_value: '[s \\in Server |-> Nil]'
- name: pendingConfIndex
  default_value: '[s \\in Server |-> 0]'
- name: uncommittedSize
  default_value: '[s \\in Server |-> 0]'
- name: isLearner
  default_value: '[s \\in Server |-> FALSE]'
- name: config
  default_value: '[s \\in Server |-> [voters: Server, learners: {}]]'
- name: readOnlyOption
  default_value: '[s \\in Server |-> "Safe"]'
actions:
- name: HandletickElection
  parameters:
  - name: s
    source: Server
  stmt: HandletickElection(s)
- name: HandletickHeartbeat
  parameters:
  - name: s
    source: Server
  stmt: HandletickHeartbeat(s)
- name: Step
  parameters:
  - name: s
    source: Server
  - name: m
    source: messages
  stmt:     /\ pc = Nil
            /\ Step(s, m) 
            /\ UNCHANGED <<pc, info, stack>>
Interactions: 
- name: HandletickElection_1
- name: HandletickHeartbeat_1
- name: HandletickHeartbeat_1_2
